# Generated by Django 5.1.2 on 2024-11-10 13:52

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_time_mailing",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                null=True,
                verbose_name="время последней рассылки",
            ),
        ),
    ]
